version: "2"
plugins:
  duplication:
    enabled: true
    exclude_patterns:
    - "**/*.spec.js"
    - "**/*.po.js"
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    exclude_patterns:
    - "**/*.po.js"
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
